services:
  postgres:
    image: postgres:16-alpine
    container_name: campaign-manager-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: campaign_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - campaing-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d campaign_manager"]
      interval: 5s
      timeout: 5s
      retries: 10
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: campaign-manager-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@campaign.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - campaing-network
    depends_on:
      - postgres
      
volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  campaing-network:
    driver: bridge